### ISSUE TITLE
False support for PHP 7

### ISSUE THREAD

**Issue by magicpush** [LExpress/symfony1#138]
"Fork of symfony 1.4 ... and PHP 7.0 support"
It's a lie.

Did you know that originally PHP 7 doesn't support memcache? Memcached must be used instead.
SURPRISE!
1. lib/vendor/symfony/lib/cache/sfMemcacheCache.class.php:45, 56
2. lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/lib/Doctrine/Cache/Memcache.php:62

Now tell me how your fork adds PHP 7 support.

**Comment by j0k3r** [comment]
Hello @magicpush 
Glad to see it's your first issue! Congrats :tada: (even if I guess you won't be that happy to remember that one in few years, anyway).

You don't need to enable Memcache to run symfony 1.4. **It is not a requirement**. 

If you run `php data/bin/check_configuration.php` it'll tell you :

```
[[WARNING]] Memcache is available: FAILED
            *** You must have memcache installed and enabled to use sfMemcacheCache class. ***
```

It's just a warning.
You can use other caching method with `sfSQLiteCache` or `sfFileCache`.

It looks like Memcache is supported in PHP 7.x using [Memcached](http://php.net/manual/fr/class.memcached.php) and there is also a package for Debian ([php7.0-memcached](https://packages.debian.org/sid/php7.0-memcached)). The only difference seems to be the classname, which is obviously different.

As you may know this fork is open source which means you can provide a [Pull Request](https://help.github.com/articles/about-pull-requests/) to add you own code. Or even [Fork](https://help.github.com/articles/fork-a-repo/) this repo and make changes on your side without contributing back to the community (which we don't encourage).

It doesn't seems to be that far complex to add support for Memcached instead of Memcache (like creating `sfMemcachedCache`). Maybe you can took some time to fix that, as it looks like it kind of blocking for you.
And it'll avoid other people to come here and surprised us with a false support of Memcache :wine_glass:

**Comment by tyx** [comment]
Be aware that we run a project with this library on PHP7.

**Comment by magicpush** [comment]
Well, I would congratulate myself if there is no issue or comment from me. That would mean that there are no problems.

Ok, I see your point, that it is not a requirement. But your team actually did some changes that are not required and doesn't really solve any bug.

Maybe later I will provide you with a pull request.
At least it is bad when sfMemcacheCahce test only for "Memcache" registered, but not "Memcached". The main problem is in this check with exception throwing.

**Comment by desyncr** [comment]
@j0k3r Is there any interest in having sfMemcachedCache implementation? I'm open to create a PR.

**Comment by j0k3r** [comment]
I'm personally not interested and don't know if other people are.

**Comment by desyncr** [comment]
Well, I'm working on a project that needs it. Rather than have to maintain my own fork I'd rather submit it here.

Technically is not different than current sfMemcacheCache, so maintenance-wise it won't be a burden.

On February 20, 2018 6:27:32 PM GMT-03:00, "Jérémy Benoist" <notifications@github.com> wrote:
>I'm personally not interested and don't know if other people are.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LExpress/symfony1/issues/138#issuecomment-367125545

-- 
Sent from mobile. Please excuse my brevity.

**Comment by e1himself** [comment]
Just for the record: as far as I understand this new class doesn't need to be a part of symfony repo -- so no need to fork it. You can create a standalone lib and link it as a composer dependency. 

As long as it's autoloadable, you should be able to use it via *factories.yml*.
